#!/usr/bin/env python3
# Fills translations/jasminekicq_<lang>.ts from the tables below (source text -> translation).
# Strings not in a table stay untranslated (English) and are listed. Languages: ru, uk.
#
#   lupdate -extensions qml,cpp,h -no-obsolete src qml -ts translations/jasminekicq_ru.ts translations/jasminekicq_uk.ts
#   python tools/translate.py
#   lrelease translations/jasminekicq_ru.ts translations/jasminekicq_uk.ts
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

RU = {
    "version %1": "версия %1",
    "An ICQ client for the kicq.ru server, ported from Jasmine IM for Android to Symbian Anna/Belle.":
        "ICQ-клиент для сервера kicq.ru, перенесённый с Jasmine IM для Android на Symbian Anna/Belle.",
    "Statuses: green - online, yellow - away, green with a badge - busy, red - offline, white - unknown (not on the server list or not yet authorized). Messages to offline contacts are stored by the server only when they are pure Latin, or Cyrillic without digits and punctuation - a limitation of the server.":
        "Статусы: зелёный — в сети, жёлтый — отошёл, зелёный со значком — занят, красный — не в сети, белый — неизвестен (нет в списке на сервере или ещё не авторизован). Сообщения контактам не в сети сервер сохраняет только если они целиком латиницей или кириллицей без цифр и знаков препинания — ограничение сервера.",
    "Enter your UIN and password.": "Введите UIN и пароль.",
    "Connection lost: %1. Reconnecting...": "Соединение потеряно: %1. Переподключение...",
    "%1 (%2) asks for your authorization.": "%1 (%2) запрашивает авторизацию.",
    "%1 (%2) asks for your authorization: %3": "%1 (%2) запрашивает авторизацию: %3",
    "asks for your authorization": "запрашивает авторизацию",
    "%1 authorized you.": "%1 авторизовал(а) вас.",
    "%1 declined your authorization request.": "%1 отклонил(а) запрос авторизации.",
    "%1 added you to their contact list.": "%1 добавил(а) вас в свой список контактов.",
    "Contact %1 added.": "Контакт %1 добавлен.",
    "%1 is already in the list.": "%1 уже есть в списке.",
    "Could not add %1 (error %2).": "Не удалось добавить %1 (ошибка %2).",
    "Contact removed.": "Контакт удалён.",
    "Could not remove the contact (error %1).": "Не удалось удалить контакт (ошибка %1).",
    "Could not rename the contact (error %1).": "Не удалось переименовать контакт (ошибка %1).",
    "Group \"%1\" created.": "Группа «%1» создана.",
    "Group \"%1\" already exists.": "Группа «%1» уже существует.",
    "Could not create the group (error %1).": "Не удалось создать группу (ошибка %1).",
    "A UIN is a number.": "UIN — это число.",
    "Not connected.": "Нет соединения.",
    "Please authorize me": "Пожалуйста, авторизуйте меня",
    "Authorization request sent.": "Запрос авторизации отправлен.",
    "Copied.": "Скопировано.",
    "Add to contact list": "Добавить в список контактов",
    "Copy UIN": "Скопировать UIN",
    "Clear history": "Очистить историю",
    "Delete all messages of this chat from the phone?": "Удалить все сообщения этого чата с телефона?",
    "Delete": "Удалить",
    "Cancel": "Отмена",
    "Copy text": "Скопировать текст",
    "Retry": "Повторить",
    "No messages yet.": "Сообщений пока нет.",
    "message": "сообщение",
    "Send": "Отправить",
    "Not in list": "Не в списке",
    "typing...": "печатает...",
    "awaiting authorization": "ожидает авторизации",
    "Hide offline contacts": "Скрыть контакты не в сети",
    "Show offline contacts": "Показать контакты не в сети",
    "New group": "Новая группа",
    "Connect": "Подключиться",
    "Disconnect": "Отключиться",
    "Settings": "Настройки",
    "About": "О программе",
    "Sign out": "Выйти",
    "Sign out? The saved password will be removed from this phone.": "Выйти? Сохранённый пароль будет удалён с этого телефона.",
    "My status": "Мой статус",
    "Add contact": "Добавить контакт",
    "Add": "Добавить",
    "UIN": "UIN",
    "nickname (optional)": "ник (необязательно)",
    "group": "группа",
    "choose...": "выбрать...",
    "Group": "Группа",
    "Create": "Создать",
    "group name": "название группы",
    "Rename contact": "Переименовать контакт",
    "Rename": "Переименовать",
    "Remove contact": "Удалить контакт",
    "Remove \"%1\" from the contact list on the server?": "Удалить «%1» из списка контактов на сервере?",
    "Remove": "Удалить",
    "Request authorization": "Запросить авторизацию",
    "connecting...": "подключение...",
    "offline": "не в сети",
    "The contact list is empty. Tap + to add someone.": "Список контактов пуст. Нажмите +, чтобы добавить кого-нибудь.",
    "Nobody is online.": "Никого нет в сети.",
    "Connecting...": "Подключение...",
    "Offline. Use the menu to connect.": "Не в сети. Подключитесь через меню.",
    "sign in to ICQ (kicq.ru)": "вход в ICQ (kicq.ru)",
    "password": "пароль",
    "show password": "показать пароль",
    "sign in automatically": "входить автоматически",
    "server": "сервер",
    "port": "порт",
    "signing in...": "вход...",
    "sign in": "войти",
    "The password travels in the classic ICQ form (obscured, not encrypted) and only its first 8 characters count - that is how this server works.":
        "Пароль передаётся в классическом виде ICQ (замаскирован, но не зашифрован), и учитываются только первые 8 символов — так устроен этот сервер.",
    "The contact is offline and the server could not store the message.": "Контакт не в сети, и сервер не смог сохранить сообщение.",
    "The contact's client does not support this message.": "Клиент контакта не поддерживает такое сообщение.",
    "Authorization required: the contact has to authorize you first.": "Нужна авторизация: сначала контакт должен авторизовать вас.",
    "You are blocked by this contact.": "Этот контакт вас заблокировал.",
    "The message was not delivered (error %1).": "Сообщение не доставлено (ошибка %1).",
    "Today": "Сегодня",
    "Yesterday": "Вчера",
    "App language": "Язык приложения",
    "System default": "Как в системе",
    "Popup for new messages": "Уведомление о новых сообщениях",
    "JasmineKICQ: new message": "JasmineKICQ: новое сообщение",
    "JasmineKICQ: %1 new messages": "JasmineKICQ: новых сообщений: %1",
    "Vibrate": "Вибрация",
    "Used when a message arrives while another application is in front. JasmineKICQ stays connected in the background.":
        "Срабатывает, когда сообщение приходит, пока открыто другое приложение. JasmineKICQ остаётся подключённым в фоне.",
    "Connect on start": "Подключаться при запуске",
    "Takes effect after the app is restarted.": "Вступает в силу после перезапуска приложения.",
    "Server: %1:%2 (change it on the sign-in page after signing out).": "Сервер: %1:%2 (меняется на странице входа после выхода).",
    "Offline": "Не в сети",
    "Online": "В сети",
    "Away": "Отошёл",
    "Not available": "Недоступен",
    "Occupied": "Занят",
    "Do not disturb": "Не беспокоить",
    "Free for chat": "Готов поболтать",
    "Invisible": "Невидимый",
    "Lunch": "Обед",
    "Evil": "Злой",
    "Depressed": "Депрессия",
    "At home": "Дома",
    "At work": "На работе",
    "Authorization request": "Запрос авторизации",
    "Authorize": "Авторизовать",
    "Decline": "Отклонить",
    "Log": "Журнал",
    "Copy log": "Скопировать журнал",
}

UK = {
    "version %1": "версія %1",
    "An ICQ client for the kicq.ru server, ported from Jasmine IM for Android to Symbian Anna/Belle.":
        "ICQ-клієнт для сервера kicq.ru, перенесений з Jasmine IM для Android на Symbian Anna/Belle.",
    "Statuses: green - online, yellow - away, green with a badge - busy, red - offline, white - unknown (not on the server list or not yet authorized). Messages to offline contacts are stored by the server only when they are pure Latin, or Cyrillic without digits and punctuation - a limitation of the server.":
        "Статуси: зелений — у мережі, жовтий — відійшов, зелений зі значком — зайнятий, червоний — не в мережі, білий — невідомий (немає в списку на сервері або ще не авторизований). Повідомлення контактам не в мережі сервер зберігає лише якщо вони повністю латиницею або кирилицею без цифр і розділових знаків — обмеження сервера.",
    "Enter your UIN and password.": "Введіть UIN і пароль.",
    "Connection lost: %1. Reconnecting...": "З'єднання втрачено: %1. Повторне підключення...",
    "%1 (%2) asks for your authorization.": "%1 (%2) просить авторизацію.",
    "%1 (%2) asks for your authorization: %3": "%1 (%2) просить авторизацію: %3",
    "asks for your authorization": "просить авторизацію",
    "%1 authorized you.": "%1 авторизував(ла) вас.",
    "%1 declined your authorization request.": "%1 відхилив(ла) запит авторизації.",
    "%1 added you to their contact list.": "%1 додав(ла) вас до свого списку контактів.",
    "Contact %1 added.": "Контакт %1 додано.",
    "%1 is already in the list.": "%1 уже є в списку.",
    "Could not add %1 (error %2).": "Не вдалося додати %1 (помилка %2).",
    "Contact removed.": "Контакт видалено.",
    "Could not remove the contact (error %1).": "Не вдалося видалити контакт (помилка %1).",
    "Could not rename the contact (error %1).": "Не вдалося перейменувати контакт (помилка %1).",
    "Group \"%1\" created.": "Групу «%1» створено.",
    "Group \"%1\" already exists.": "Група «%1» уже існує.",
    "Could not create the group (error %1).": "Не вдалося створити групу (помилка %1).",
    "A UIN is a number.": "UIN — це число.",
    "Not connected.": "Немає з'єднання.",
    "Please authorize me": "Будь ласка, авторизуйте мене",
    "Authorization request sent.": "Запит авторизації надіслано.",
    "Copied.": "Скопійовано.",
    "Add to contact list": "Додати до списку контактів",
    "Copy UIN": "Скопіювати UIN",
    "Clear history": "Очистити історію",
    "Delete all messages of this chat from the phone?": "Видалити всі повідомлення цього чату з телефону?",
    "Delete": "Видалити",
    "Cancel": "Скасувати",
    "Copy text": "Скопіювати текст",
    "Retry": "Повторити",
    "No messages yet.": "Повідомлень поки немає.",
    "message": "повідомлення",
    "Send": "Надіслати",
    "Not in list": "Не в списку",
    "typing...": "друкує...",
    "awaiting authorization": "очікує авторизації",
    "Hide offline contacts": "Сховати контакти не в мережі",
    "Show offline contacts": "Показати контакти не в мережі",
    "New group": "Нова група",
    "Connect": "Підключитися",
    "Disconnect": "Відключитися",
    "Settings": "Налаштування",
    "About": "Про програму",
    "Sign out": "Вийти",
    "Sign out? The saved password will be removed from this phone.": "Вийти? Збережений пароль буде видалено з цього телефону.",
    "My status": "Мій статус",
    "Add contact": "Додати контакт",
    "Add": "Додати",
    "UIN": "UIN",
    "nickname (optional)": "нік (необов'язково)",
    "group": "група",
    "choose...": "обрати...",
    "Group": "Група",
    "Create": "Створити",
    "group name": "назва групи",
    "Rename contact": "Перейменувати контакт",
    "Rename": "Перейменувати",
    "Remove contact": "Видалити контакт",
    "Remove \"%1\" from the contact list on the server?": "Видалити «%1» зі списку контактів на сервері?",
    "Remove": "Видалити",
    "Request authorization": "Запросити авторизацію",
    "connecting...": "підключення...",
    "offline": "не в мережі",
    "The contact list is empty. Tap + to add someone.": "Список контактів порожній. Натисніть +, щоб когось додати.",
    "Nobody is online.": "Нікого немає в мережі.",
    "Connecting...": "Підключення...",
    "Offline. Use the menu to connect.": "Не в мережі. Підключіться через меню.",
    "sign in to ICQ (kicq.ru)": "вхід до ICQ (kicq.ru)",
    "password": "пароль",
    "show password": "показати пароль",
    "sign in automatically": "входити автоматично",
    "server": "сервер",
    "port": "порт",
    "signing in...": "вхід...",
    "sign in": "увійти",
    "The password travels in the classic ICQ form (obscured, not encrypted) and only its first 8 characters count - that is how this server works.":
        "Пароль передається в класичному вигляді ICQ (замаскований, але не зашифрований), і враховуються лише перші 8 символів — так влаштовано цей сервер.",
    "The contact is offline and the server could not store the message.": "Контакт не в мережі, і сервер не зміг зберегти повідомлення.",
    "The contact's client does not support this message.": "Клієнт контакту не підтримує таке повідомлення.",
    "Authorization required: the contact has to authorize you first.": "Потрібна авторизація: спочатку контакт має авторизувати вас.",
    "You are blocked by this contact.": "Цей контакт вас заблокував.",
    "The message was not delivered (error %1).": "Повідомлення не доставлено (помилка %1).",
    "Today": "Сьогодні",
    "Yesterday": "Учора",
    "App language": "Мова застосунку",
    "System default": "Як у системі",
    "Popup for new messages": "Сповіщення про нові повідомлення",
    "JasmineKICQ: new message": "JasmineKICQ: нове повідомлення",
    "JasmineKICQ: %1 new messages": "JasmineKICQ: нових повідомлень: %1",
    "Vibrate": "Вібрація",
    "Used when a message arrives while another application is in front. JasmineKICQ stays connected in the background.":
        "Спрацьовує, коли повідомлення надходить, поки відкрито інший застосунок. JasmineKICQ залишається підключеним у фоні.",
    "Connect on start": "Підключатися під час запуску",
    "Takes effect after the app is restarted.": "Набуває чинності після перезапуску застосунку.",
    "Server: %1:%2 (change it on the sign-in page after signing out).": "Сервер: %1:%2 (змінюється на сторінці входу після виходу).",
    "Offline": "Не в мережі",
    "Online": "У мережі",
    "Away": "Відійшов",
    "Not available": "Недоступний",
    "Occupied": "Зайнятий",
    "Do not disturb": "Не турбувати",
    "Free for chat": "Готовий поспілкуватися",
    "Invisible": "Невидимий",
    "Lunch": "Обід",
    "Evil": "Злий",
    "Depressed": "Депресія",
    "At home": "Удома",
    "At work": "На роботі",
    "Authorization request": "Запит авторизації",
    "Authorize": "Авторизувати",
    "Decline": "Відхилити",
    "Log": "Журнал",
    "Copy log": "Скопіювати журнал",
}


def fill(lang, table):
    path = os.path.join(ROOT, "translations", "jasminekicq_%s.ts" % lang)
    tree = ET.parse(path)
    missing = []
    for msg in tree.getroot().iter("message"):
        src = msg.find("source").text or ""
        tr = msg.find("translation")
        text = table.get(src)
        if text is None:
            missing.append(src)
            continue
        tr.text = text
        if "type" in tr.attrib:
            del tr.attrib["type"]
    tree.write(path, encoding="utf-8", xml_declaration=True)
    # ET drops the DOCTYPE line lrelease is happy without; keep the file readable
    print("%s: %d missing" % (lang, len(missing)))
    for m in missing:
        print("   ", m)


if __name__ == "__main__":
    fill("ru", RU)
    fill("uk", UK)
